version: "3.8"

name: devstack

services:
  postgresql:
    image: postgres:17
    networks:
      - bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    build:
      context: ./services/rabbitmq
      dockerfile: Dockerfile
    networks:
      - bridge
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq:Z
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:8.2
    networks:
      - bridge
    ports:
      - "6379:6379"

  n8n:
    image: n8nio/n8n:latest
    networks:
      - bridge
    environment:
      - DB_TYPE=sqlite

      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin

      # Webhook
      - WEBHOOK_URL=https://n8n.mnabila.my.id

      # Timezone
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
    volumes:
      - ./data/n8n:/home/node/.n8n:Z
    ports:
      - "5678:5678"

networks:
  bridge:
    driver: bridge
